
name: Assignment Overview
description: Starting point for new Data Lab projects
title: "[COUNTRY] | [PROJECT]"
labels: data lab assignment
body:
- type: markdown
  attributes:
    value: |
      Congratulations on starting a new project! Please enter the basic information here.
- type: input
  id: contact
  attributes:
    label: Client Contact Email(s)
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  id: charge-code
  attributes:
    label: Project Charge Code
    description: Also tell us, what did you expect to happen?
  validations:
    required: false
- type: textarea
  id: manager
  attributes:
    label: Project Manager
  validations:
    required: false
- type: textarea
  id: share-point
  attributes:
    label: Project Sharepoint URL
- type: textarea
  id: assignment-summary
  attributes:
    label: Project Assignment
    description: Please provide a summary of the project and assignment
- type: markdown
  attributes:
    value: |
      Please add a task list, below, with individial tasks. Once all tasks are reviewed by the project manager and completed, this issue may be closed.
